<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Pages\Front\Profile\Security.cshtml" />
    <Content Remove="Pages\Front\SocialMedia\Instagram\Post\Edit.cshtml" />
    <Content Remove="Pages\Shared\Partials\_Aside.cshtml" />
    <Content Remove="Pages\Shared\_LayoutFront.cshtml" />
    <Content Remove="Pages\Shared\_LayoutProfile.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="TagHelpers\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CookieManager" Version="2.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.6" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.7" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Pages\Shared\Partials\_Aside.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="Pages\Front\Profile\Security.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\Front\SocialMedia\Instagram\Post\Edit.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\Shared\Partials\_Aside.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\Shared\_LayoutFront.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\Shared\_LayoutProfile.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Pages\Front\Profile\Security.cshtml" />
    <None Include="Pages\Front\SocialMedia\Instagram\Post\Edit.cshtml" />
    <None Include="Pages\Shared\Partials\_Aside.cshtml" />
    <None Include="Pages\Shared\_LayoutProfile.cshtml" />
    <None Include="wwwroot\assets\img\customizer\border-dark.svg" />
    <None Include="wwwroot\assets\img\customizer\border.svg" />
    <None Include="wwwroot\assets\img\customizer\collapsed-dark.svg" />
    <None Include="wwwroot\assets\img\customizer\collapsed.svg" />
    <None Include="wwwroot\assets\img\customizer\compact-dark.svg" />
    <None Include="wwwroot\assets\img\customizer\compact.svg" />
    <None Include="wwwroot\assets\img\customizer\dark-dark.svg" />
    <None Include="wwwroot\assets\img\customizer\dark.svg" />
    <None Include="wwwroot\assets\img\customizer\default-dark.svg" />
    <None Include="wwwroot\assets\img\customizer\default.svg" />
    <None Include="wwwroot\assets\img\customizer\expanded-dark.svg" />
    <None Include="wwwroot\assets\img\customizer\expanded.svg" />
    <None Include="wwwroot\assets\img\customizer\hidden-dark.svg" />
    <None Include="wwwroot\assets\img\customizer\hidden.svg" />
    <None Include="wwwroot\assets\img\customizer\horizontal-fixed-dark.svg" />
    <None Include="wwwroot\assets\img\customizer\horizontal-fixed.svg" />
    <None Include="wwwroot\assets\img\customizer\horizontal-static-dark.svg" />
    <None Include="wwwroot\assets\img\customizer\horizontal-static.svg" />
    <None Include="wwwroot\assets\img\customizer\light-dark.svg" />
    <None Include="wwwroot\assets\img\customizer\light.svg" />
    <None Include="wwwroot\assets\img\customizer\ltr-dark.svg" />
    <None Include="wwwroot\assets\img\customizer\ltr.svg" />
    <None Include="wwwroot\assets\img\customizer\rtl-dark.svg" />
    <None Include="wwwroot\assets\img\customizer\rtl.svg" />
    <None Include="wwwroot\assets\img\customizer\semi-dark-dark.svg" />
    <None Include="wwwroot\assets\img\customizer\semi-dark.svg" />
    <None Include="wwwroot\assets\img\customizer\static-dark.svg" />
    <None Include="wwwroot\assets\img\customizer\static.svg" />
    <None Include="wwwroot\assets\img\customizer\sticky-dark.svg" />
    <None Include="wwwroot\assets\img\customizer\sticky.svg" />
    <None Include="wwwroot\assets\img\customizer\system-dark.svg" />
    <None Include="wwwroot\assets\img\customizer\system.svg" />
    <None Include="wwwroot\assets\img\customizer\vertical-dark.svg" />
    <None Include="wwwroot\assets\img\customizer\vertical.svg" />
    <None Include="wwwroot\assets\img\customizer\wide-dark.svg" />
    <None Include="wwwroot\assets\img\customizer\wide.svg" />
    <None Include="wwwroot\assets\json\ajax.php" />
    <None Include="wwwroot\assets\js\app-access-permission.js" />
    <None Include="wwwroot\assets\js\app-access-roles.js" />
    <None Include="wwwroot\assets\js\app-calendar-events.js" />
    <None Include="wwwroot\assets\js\app-calendar.js" />
    <None Include="wwwroot\assets\js\app-chat.js" />
    <None Include="wwwroot\assets\js\app-email.js" />
    <None Include="wwwroot\assets\js\app-invoice-add.js" />
    <None Include="wwwroot\assets\js\app-invoice-edit.js" />
    <None Include="wwwroot\assets\js\app-invoice-list.js" />
    <None Include="wwwroot\assets\js\app-invoice-print.js" />
    <None Include="wwwroot\assets\js\app-kanban.js" />
    <None Include="wwwroot\assets\js\app-user-list.js" />
    <None Include="wwwroot\assets\js\app-user-view-account.js" />
    <None Include="wwwroot\assets\js\app-user-view-billing.js" />
    <None Include="wwwroot\assets\js\app-user-view-security.js" />
    <None Include="wwwroot\assets\js\app-user-view.js" />
    <None Include="wwwroot\assets\js\cards-actions.js" />
    <None Include="wwwroot\assets\js\cards-analytics.js" />
    <None Include="wwwroot\assets\js\cards-statistics.js" />
    <None Include="wwwroot\assets\js\charts-apex.js" />
    <None Include="wwwroot\assets\js\charts-chartjs.js" />
    <None Include="wwwroot\assets\js\config.js" />
    <None Include="wwwroot\assets\js\dashboards-analytics.js" />
    <None Include="wwwroot\assets\js\dashboards-crm.js" />
    <None Include="wwwroot\assets\js\dashboards-ecommerce.js" />
    <None Include="wwwroot\assets\js\extended-ui-blockui.js" />
    <None Include="wwwroot\assets\js\extended-ui-drag-and-drop.js" />
    <None Include="wwwroot\assets\js\extended-ui-media-player.js" />
    <None Include="wwwroot\assets\js\extended-ui-misc-clipboardjs.js" />
    <None Include="wwwroot\assets\js\extended-ui-misc-idle-timer.js" />
    <None Include="wwwroot\assets\js\extended-ui-misc-numeraljs.js" />
    <None Include="wwwroot\assets\js\extended-ui-perfect-scrollbar.js" />
    <None Include="wwwroot\assets\js\extended-ui-star-ratings.js" />
    <None Include="wwwroot\assets\js\extended-ui-sweetalert2.js" />
    <None Include="wwwroot\assets\js\extended-ui-timeline.js" />
    <None Include="wwwroot\assets\js\extended-ui-tour.js" />
    <None Include="wwwroot\assets\js\extended-ui-treeview.js" />
    <None Include="wwwroot\assets\js\form-basic-inputs.js" />
    <None Include="wwwroot\assets\js\form-layouts.js" />
    <None Include="wwwroot\assets\js\form-validation.js" />
    <None Include="wwwroot\assets\js\form-wizard-icons.js" />
    <None Include="wwwroot\assets\js\form-wizard-numbered.js" />
    <None Include="wwwroot\assets\js\form-wizard-validation.js" />
    <None Include="wwwroot\assets\js\forms-editors.js" />
    <None Include="wwwroot\assets\js\forms-extras.js" />
    <None Include="wwwroot\assets\js\forms-file-upload.js" />
    <None Include="wwwroot\assets\js\forms-pickers.js" />
    <None Include="wwwroot\assets\js\forms-selects.js" />
    <None Include="wwwroot\assets\js\forms-sliders.js" />
    <None Include="wwwroot\assets\js\forms-tagify.js" />
    <None Include="wwwroot\assets\js\forms-typeahead.js" />
    <None Include="wwwroot\assets\js\main.js" />
    <None Include="wwwroot\assets\js\maps-leaflet.js" />
    <None Include="wwwroot\assets\js\modal-add-new-address.js" />
    <None Include="wwwroot\assets\js\modal-add-new-cc.js" />
    <None Include="wwwroot\assets\js\modal-add-permission.js" />
    <None Include="wwwroot\assets\js\modal-add-role.js" />
    <None Include="wwwroot\assets\js\modal-create-app.js" />
    <None Include="wwwroot\assets\js\modal-edit-cc.js" />
    <None Include="wwwroot\assets\js\modal-edit-permission.js" />
    <None Include="wwwroot\assets\js\modal-edit-user.js" />
    <None Include="wwwroot\assets\js\modal-enable-otp.js" />
    <None Include="wwwroot\assets\js\modal-share-project.js" />
    <None Include="wwwroot\assets\js\modal-two-factor-auth.js" />
    <None Include="wwwroot\assets\js\offcanvas-add-payment.js" />
    <None Include="wwwroot\assets\js\offcanvas-send-invoice.js" />
    <None Include="wwwroot\assets\js\pages-account-settings-account.js" />
    <None Include="wwwroot\assets\js\pages-account-settings-billing.js" />
    <None Include="wwwroot\assets\js\pages-account-settings-security.js" />
    <None Include="wwwroot\assets\js\pages-auth-multisteps.js" />
    <None Include="wwwroot\assets\js\pages-auth-two-steps.js" />
    <None Include="wwwroot\assets\js\pages-auth.js" />
    <None Include="wwwroot\assets\js\pages-pricing.js" />
    <None Include="wwwroot\assets\js\pages-profile.js" />
    <None Include="wwwroot\assets\js\tables-datatables-advanced.js" />
    <None Include="wwwroot\assets\js\tables-datatables-basic.js" />
    <None Include="wwwroot\assets\js\tables-datatables-extensions.js" />
    <None Include="wwwroot\assets\js\ui-carousel.js" />
    <None Include="wwwroot\assets\js\ui-modals.js" />
    <None Include="wwwroot\assets\js\ui-navbar.js" />
    <None Include="wwwroot\assets\js\ui-popover.js" />
    <None Include="wwwroot\assets\js\ui-toasts.js" />
    <None Include="wwwroot\assets\js\wizard-ex-checkout.js" />
    <None Include="wwwroot\assets\js\wizard-ex-create-deal.js" />
    <None Include="wwwroot\assets\js\wizard-ex-property-listing.js" />
    <None Include="wwwroot\assets\svg\flags\au.svg" />
    <None Include="wwwroot\assets\svg\flags\br.svg" />
    <None Include="wwwroot\assets\svg\flags\cn.svg" />
    <None Include="wwwroot\assets\svg\flags\fr.svg" />
    <None Include="wwwroot\assets\svg\flags\in.svg" />
    <None Include="wwwroot\assets\svg\flags\pt.svg" />
    <None Include="wwwroot\assets\svg\flags\us.svg" />
    <None Include="wwwroot\assets\svg\icons\credit-card.svg" />
    <None Include="wwwroot\assets\svg\icons\discord.svg" />
    <None Include="wwwroot\assets\svg\icons\form-wizard-account.svg" />
    <None Include="wwwroot\assets\svg\icons\form-wizard-address.svg" />
    <None Include="wwwroot\assets\svg\icons\form-wizard-personal.svg" />
    <None Include="wwwroot\assets\svg\icons\form-wizard-social-link.svg" />
    <None Include="wwwroot\assets\svg\icons\form-wizard-submit.svg" />
    <None Include="wwwroot\assets\svg\icons\gift.svg" />
    <None Include="wwwroot\assets\svg\icons\keyboard.svg" />
    <None Include="wwwroot\assets\svg\icons\laptop.svg" />
    <None Include="wwwroot\assets\svg\icons\lightbulb.svg" />
    <None Include="wwwroot\assets\svg\icons\rocket.svg" />
    <None Include="wwwroot\assets\svg\icons\wizard-checkout-address.svg" />
    <None Include="wwwroot\assets\svg\icons\wizard-checkout-cart.svg" />
    <None Include="wwwroot\assets\svg\icons\wizard-checkout-confirmation.svg" />
    <None Include="wwwroot\assets\svg\icons\wizard-checkout-payment.svg" />
    <None Include="wwwroot\assets\vendor\fonts\boxicons\boxicons.woff2" />
    <None Include="wwwroot\assets\vendor\fonts\boxicons\boxiconsd41dd41d.svg" />
    <None Include="wwwroot\assets\vendor\fonts\IRANSans\woff2\IRANSans-Black.woff2" />
    <None Include="wwwroot\assets\vendor\fonts\IRANSans\woff2\IRANSans-Bold.woff2" />
    <None Include="wwwroot\assets\vendor\fonts\IRANSans\woff2\IRANSans-DemiBold.woff2" />
    <None Include="wwwroot\assets\vendor\fonts\IRANSans\woff2\IRANSans-ExtraBlack.woff2" />
    <None Include="wwwroot\assets\vendor\fonts\IRANSans\woff2\IRANSans-ExtraBold.woff2" />
    <None Include="wwwroot\assets\vendor\fonts\IRANSans\woff2\IRANSans-Heavy.woff2" />
    <None Include="wwwroot\assets\vendor\fonts\IRANSans\woff2\IRANSans-Light.woff2" />
    <None Include="wwwroot\assets\vendor\fonts\IRANSans\woff2\IRANSans-Medium.woff2" />
    <None Include="wwwroot\assets\vendor\fonts\IRANSans\woff2\IRANSans-Regular.woff2" />
    <None Include="wwwroot\assets\vendor\fonts\IRANSans\woff2\IRANSans-Thin.woff2" />
    <None Include="wwwroot\assets\vendor\fonts\IRANSans\woff2\IRANSans-UltraLight.woff2" />
    <None Include="wwwroot\assets\vendor\fonts\materialdesignicons\materialdesignicons-webfont9445.woff2" />
    <None Include="wwwroot\assets\vendor\fonts\Shabnam\Shabnam-Bold.woff2" />
    <None Include="wwwroot\assets\vendor\fonts\Shabnam\Shabnam-Light.woff2" />
    <None Include="wwwroot\assets\vendor\fonts\Shabnam\Shabnam-Medium.woff2" />
    <None Include="wwwroot\assets\vendor\fonts\Shabnam\Shabnam-Thin.woff2" />
    <None Include="wwwroot\assets\vendor\fonts\Shabnam\Shabnam.woff2" />
    <None Include="wwwroot\assets\vendor\js\bootstrap.js" />
    <None Include="wwwroot\assets\vendor\js\dropdown-hover.js" />
    <None Include="wwwroot\assets\vendor\js\helpers.js" />
    <None Include="wwwroot\assets\vendor\js\mega-dropdown.js" />
    <None Include="wwwroot\assets\vendor\js\menu.js" />
    <None Include="wwwroot\assets\vendor\js\template-customizer.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\bundle\full.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\bundle\full.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\bundle\popular.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\bundle\popular.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\core\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\core\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\ar_MA.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\ar_MA.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\bg_BG.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\bg_BG.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\ca_ES.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\ca_ES.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\cs_CZ.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\cs_CZ.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\da_DK.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\da_DK.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\de_DE.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\de_DE.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\el_GR.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\el_GR.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\en_US.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\en_US.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\es_CL.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\es_CL.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\es_ES.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\es_ES.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\eu_ES.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\eu_ES.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\fa_IR.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\fa_IR.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\fi_FI.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\fi_FI.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\fr_BE.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\fr_BE.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\fr_FR.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\fr_FR.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\he_IL.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\he_IL.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\hi_IN.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\hi_IN.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\hu_HU.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\hu_HU.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\id_ID.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\id_ID.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\it_IT.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\it_IT.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\ja_JP.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\ja_JP.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\nl_BE.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\nl_BE.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\nl_NL.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\nl_NL.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\no_NO.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\no_NO.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\pl_PL.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\pl_PL.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\pt_BR.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\pt_BR.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\pt_PT.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\pt_PT.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\ro_RO.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\ro_RO.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\ru_RU.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\ru_RU.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\sk_SK.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\sk_SK.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\sq_AL.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\sq_AL.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\sr_RS.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\sr_RS.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\sv_SE.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\sv_SE.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\th_TH.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\th_TH.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\tr_TR.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\tr_TR.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\ua_UA.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\ua_UA.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\vi_VN.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\vi_VN.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\zh_CN.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\zh_CN.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\zh_TW.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\locales\zh_TW.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-alias\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-alias\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-aria\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-aria\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-auto-focus\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-auto-focus\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-bootstrap3\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-bootstrap3\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-bootstrap5\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-bootstrap5\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-bootstrap\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-bootstrap\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-bulma\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-bulma\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-declarative\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-declarative\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-default-submit\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-default-submit\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-dependency\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-dependency\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-excluded\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-excluded\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-field-status\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-field-status\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-foundation\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-foundation\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-framework\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-framework\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-icon\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-icon\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-international-telephone-input\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-international-telephone-input\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-j\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-j\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-l10n\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-l10n\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-mailgun\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-mailgun\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-mandatory-icon\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-mandatory-icon\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-materialize\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-materialize\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-message\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-message\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-milligram\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-milligram\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-mini\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-mini\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-mui\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-mui\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-password-strength\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-password-strength\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-pure\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-pure\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-recaptcha3-token\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-recaptcha3-token\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-recaptcha3\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-recaptcha3\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-recaptcha\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-recaptcha\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-semantic\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-semantic\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-sequence\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-sequence\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-shoelace\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-shoelace\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-spectre\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-spectre\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-start-end-date\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-start-end-date\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-submit-button\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-submit-button\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-tachyons\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-tachyons\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-tooltip\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-tooltip\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-transformer\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-transformer\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-trigger\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-trigger\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-turnstile\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-turnstile\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-turret\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-turret\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-typing-animation\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-typing-animation\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-ui-kit\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-ui-kit\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-wizard\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\plugin-wizard\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-base64\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-base64\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-between\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-between\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-bic\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-bic\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-blank\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-blank\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-callback\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-callback\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-choice\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-choice\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-color\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-color\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-credit-card\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-credit-card\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-cusip\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-cusip\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-date\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-date\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-different\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-different\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-digits\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-digits\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-ean\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-ean\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-ein\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-ein\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-email-address\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-email-address\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-file\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-file\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-greater-than\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-greater-than\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-grid\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-grid\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-hex\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-hex\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-iban\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-iban\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-identical\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-identical\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-id\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-id\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-imei\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-imei\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-imo\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-imo\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-integer\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-integer\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-ip\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-ip\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-isbn\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-isbn\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-isin\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-isin\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-ismn\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-ismn\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-issn\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-issn\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-less-than\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-less-than\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-mac\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-mac\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-meid\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-meid\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-not-empty\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-not-empty\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-numeric\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-numeric\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-phone\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-phone\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-promise\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-promise\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-regexp\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-regexp\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-remote\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-remote\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-rtn\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-rtn\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-sedol\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-sedol\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-siren\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-siren\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-siret\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-siret\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-step\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-step\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-string-case\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-string-case\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-string-length\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-string-length\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-uri\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-uri\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-uuid\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-uuid\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-vat\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-vat\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-vin\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-vin\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-zip-code\index.js" />
    <None Include="wwwroot\assets\vendor\libs\%40form-validation\umd\validator-zip-code\index.min.js" />
    <None Include="wwwroot\assets\vendor\libs\animate-on-scroll\animate-on-scroll.js" />
    <None Include="wwwroot\assets\vendor\libs\apex-charts\apexcharts.js" />
    <None Include="wwwroot\assets\vendor\libs\autosize\autosize.js" />
    <None Include="wwwroot\assets\vendor\libs\block-ui\block-ui.js" />
    <None Include="wwwroot\assets\vendor\libs\bloodhound\bloodhound.js" />
    <None Include="wwwroot\assets\vendor\libs\bootstrap-datepicker\bootstrap-datepicker.js" />
    <None Include="wwwroot\assets\vendor\libs\bootstrap-daterangepicker\bootstrap-daterangepicker.js" />
    <None Include="wwwroot\assets\vendor\libs\bootstrap-maxlength\bootstrap-maxlength.js" />
    <None Include="wwwroot\assets\vendor\libs\bootstrap-select\bootstrap-select.js" />
    <None Include="wwwroot\assets\vendor\libs\bs-stepper\bs-stepper.js" />
    <None Include="wwwroot\assets\vendor\libs\chartjs\chartjs.js" />
    <None Include="wwwroot\assets\vendor\libs\cleavejs\cleave-phone.js" />
    <None Include="wwwroot\assets\vendor\libs\cleavejs\cleave.js" />
    <None Include="wwwroot\assets\vendor\libs\clipboard\clipboard.js" />
    <None Include="wwwroot\assets\vendor\libs\datatables-bs5\datatables-bootstrap5.js" />
    <None Include="wwwroot\assets\vendor\libs\dropzone\dropzone.js" />
    <None Include="wwwroot\assets\vendor\libs\flatpickr\fa-jdate.js" />
    <None Include="wwwroot\assets\vendor\libs\flatpickr\fa.js" />
    <None Include="wwwroot\assets\vendor\libs\flatpickr\flatpickr-jdate.js" />
    <None Include="wwwroot\assets\vendor\libs\formvalidation\dist\js\FormValidation.min.js" />
    <None Include="wwwroot\assets\vendor\libs\formvalidation\dist\js\plugins\AutoFocus.min.js" />
    <None Include="wwwroot\assets\vendor\libs\formvalidation\dist\js\plugins\Bootstrap5.min.js" />
    <None Include="wwwroot\assets\vendor\libs\fullcalendar\fullcalendar.js" />
    <None Include="wwwroot\assets\vendor\libs\hammer\hammer.js" />
    <None Include="wwwroot\assets\vendor\libs\i18n\i18n.js" />
    <None Include="wwwroot\assets\vendor\libs\idletimer\idletimer.js" />
    <None Include="wwwroot\assets\vendor\libs\jdate\jdate.js" />
    <None Include="wwwroot\assets\vendor\libs\jkanban\jkanban.js" />
    <None Include="wwwroot\assets\vendor\libs\jquery-repeater\jquery-repeater.js" />
    <None Include="wwwroot\assets\vendor\libs\jquery-sticky\jquery-sticky.js" />
    <None Include="wwwroot\assets\vendor\libs\jquery-timepicker\jquery-timepicker.js" />
    <None Include="wwwroot\assets\vendor\libs\jquery\jquery.js" />
    <None Include="wwwroot\assets\vendor\libs\jstree\jstree.js" />
    <None Include="wwwroot\assets\vendor\libs\leaflet\leaflet.js" />
    <None Include="wwwroot\assets\vendor\libs\masonry\masonry.js" />
    <None Include="wwwroot\assets\vendor\libs\moment\moment.js" />
    <None Include="wwwroot\assets\vendor\libs\node-waves\node-waves.js" />
    <None Include="wwwroot\assets\vendor\libs\nouislider\nouislider.js" />
    <None Include="wwwroot\assets\vendor\libs\numeral\numeral.js" />
    <None Include="wwwroot\assets\vendor\libs\perfect-scrollbar\perfect-scrollbar.js" />
    <None Include="wwwroot\assets\vendor\libs\pickr\pickr.js" />
    <None Include="wwwroot\assets\vendor\libs\plyr\plyr.js" />
    <None Include="wwwroot\assets\vendor\libs\popper\popper.js" />
    <None Include="wwwroot\assets\vendor\libs\quill\fonts\KaTeX_AMS-Regular.woff2" />
    <None Include="wwwroot\assets\vendor\libs\quill\fonts\KaTeX_Caligraphic-Bold.woff2" />
    <None Include="wwwroot\assets\vendor\libs\quill\fonts\KaTeX_Caligraphic-Regular.woff2" />
    <None Include="wwwroot\assets\vendor\libs\quill\fonts\KaTeX_Fraktur-Bold.woff2" />
    <None Include="wwwroot\assets\vendor\libs\quill\fonts\KaTeX_Fraktur-Regular.woff2" />
    <None Include="wwwroot\assets\vendor\libs\quill\fonts\KaTeX_Main-Bold.woff2" />
    <None Include="wwwroot\assets\vendor\libs\quill\fonts\KaTeX_Main-BoldItalic.woff2" />
    <None Include="wwwroot\assets\vendor\libs\quill\fonts\KaTeX_Main-Italic.woff2" />
    <None Include="wwwroot\assets\vendor\libs\quill\fonts\KaTeX_Main-Regular.woff2" />
    <None Include="wwwroot\assets\vendor\libs\quill\fonts\KaTeX_Math-BoldItalic.woff2" />
    <None Include="wwwroot\assets\vendor\libs\quill\fonts\KaTeX_Math-Italic.woff2" />
    <None Include="wwwroot\assets\vendor\libs\quill\fonts\KaTeX_SansSerif-Bold.woff2" />
    <None Include="wwwroot\assets\vendor\libs\quill\fonts\KaTeX_SansSerif-Italic.woff2" />
    <None Include="wwwroot\assets\vendor\libs\quill\fonts\KaTeX_SansSerif-Regular.woff2" />
    <None Include="wwwroot\assets\vendor\libs\quill\fonts\KaTeX_Script-Regular.woff2" />
    <None Include="wwwroot\assets\vendor\libs\quill\fonts\KaTeX_Size1-Regular.woff2" />
    <None Include="wwwroot\assets\vendor\libs\quill\fonts\KaTeX_Size2-Regular.woff2" />
    <None Include="wwwroot\assets\vendor\libs\quill\fonts\KaTeX_Size3-Regular.woff2" />
    <None Include="wwwroot\assets\vendor\libs\quill\fonts\KaTeX_Size4-Regular.woff2" />
    <None Include="wwwroot\assets\vendor\libs\quill\fonts\KaTeX_Typewriter-Regular.woff2" />
    <None Include="wwwroot\assets\vendor\libs\quill\katex.js" />
    <None Include="wwwroot\assets\vendor\libs\quill\quill.js" />
    <None Include="wwwroot\assets\vendor\libs\rateyo\rateyo.js" />
    <None Include="wwwroot\assets\vendor\libs\select2\select2.js" />
    <None Include="wwwroot\assets\vendor\libs\shepherd\shepherd.js" />
    <None Include="wwwroot\assets\vendor\libs\sortablejs\sortable.js" />
    <None Include="wwwroot\assets\vendor\libs\sweetalert2\sweetalert2.js" />
    <None Include="wwwroot\assets\vendor\libs\swiper\swiper.js" />
    <None Include="wwwroot\assets\vendor\libs\tagify\tagify.js" />
    <None Include="wwwroot\assets\vendor\libs\toastr\toastr.js" />
    <None Include="wwwroot\assets\vendor\libs\typeahead-js\typeahead.js" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Pages\Shared\_LayoutProfile.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Pages\Front\Profile\Security.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Pages\Shared\_LayoutFront.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Pages\Front\SocialMedia\Instagram\Post\Edit.cshtml" />
  </ItemGroup>

</Project>
