<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Pages\Front\Profile\Security.cshtml" />
    <Content Remove="Pages\Shared\Partials\_Aside.cshtml" />
    <Content Remove="Pages\Shared\_LayoutFront.cshtml" />
    <Content Remove="Pages\Shared\_LayoutProfile.cshtml" />
    <Content Remove="Pages\Instagram\Post\Edit.cshtml" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="CookieManager" Version="2.0.1" />
	  <PackageReference Include="HttpToSocks5Proxy" Version="1.4.0" />
	  <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.4" />
	  <PackageReference Include="CookieManager" Version="2.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.6" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	  <PackageReference Include="Telegram.Bot" Version="22.3.0" />
	  <PackageReference Include="System.Drawing.Common" Version="8.0.7" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Pages\Shared\Partials\_Aside.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="Pages\Front\Profile\Security.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\Shared\Partials\_Aside.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\Shared\_LayoutFront.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Pages\Front\Profile\Security.cshtml" />
    <None Include="Pages\Instagram\Post\Edit.cshtml" />
    <None Include="Pages\Shared\Partials\_Aside.cshtml" />
    <None Include="Pages\Shared\_LayoutProfile.cshtml" />
    <None Include="wwwroot\ckeditor\.circleci\config.yml" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Pages\Front\Profile\Security.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Pages\Shared\_LayoutFront.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="_ViewStart.cshtml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
